library(tidyverse)

## Variation
## Visualizing Distributions
#use bar chart to examine the distribution of a categorical variable
ggplot(data=diamonds) +
  geom_bar(mapping=aes(x=cut))

#use dplyr::count to count how many observations occured with x value
diamonds %>%
  count(cut)

#use histogram to examine the distribution of a continuous variable
ggplot(data=diamonds) +
  geom_histogram(mapping=aes(x=carat),binwidth=0.5)

#use dplyr to get the same information
diamonds %>%
  count(cut_width(carat,0.5))

#zoom into diamonds with a size of less than 3 carat and smaller binwidth
smaller <- diamonds %>%
  filter(carat<3)
ggplot(data=smaller,mapping=aes(x=carat)) +
  geom_histogram(binwidth = 0.1)

#use geom_freqpoly to overlay multiple histogram in the same plot
ggplot(data=smaller,mapping=aes(x=carat,color=cut)) +
  geom_freqpoly(binwidth=0.1)

## Typical Value
#question to find information from data, look something unexpected
#1. which values are the most common?
#2. Which values are rare? why? does that match your expectation?
#example of questions generated by below graph
#1. why are there more diamonds at whole carats and common fractions of carats?
#2. why are there more diamonds slightly to to the right than 
#   to the left of each peak?
#3. why are there no diamonds bigger than three carat?
ggplot(data=smaller,mapping=aes(x=carat))+
  geom_histogram(binwidth=0.01)
#cluster of similar value suggest that subgroup exist in the data, to understand 
#subgroup

#1. how are the observation within each cluster similar to each other?
#2. how are the observation in separate clusters different from each other?
#3. how to explain or describe the clusters?
#4. why might the appear of clusters be misleading?
ggplot(data=faithful,mapping=aes(x=eruptions))+
  geom_histogram(binwidth=0.25)

## Unusual Values
#evidence of outliers is the unusually wide limits on the y-axis
ggplot(diamonds)+
  geom_histogram(mapping=aes(x=y),binwidth=0.5)

#zoom in to see unusual value
ggplot(diamonds)+
  geom_histogram(mapping=aes(x=y),binwidth=0.5)+
  coord_cartesian(ylim=c(0,50))

#pluck unusual values with dplyr
unusual <- diamonds %>%
  filter(y<3|y>20) %>%
  arrange(y)

## Exercise
#1.Explore distributions of x, y, and z
ggplot(diamonds) +
  geom_histogram(mapping=aes(x=x),binwidth=0.5)
count(diamonds,cut_width(x,0.5))
ggplot(diamonds) +
  geom_histogram(mapping=aes(x=y),binwidth=0.5)
count(diamonds,cut_width(y,0.5))
ggplot(diamonds) +
  geom_histogram(mapping=aes(x=z),binwidth=0.5)
count(diamonds,cut_width(z,0.5))
#there are unusually large value on y and z

#2.Explore distributions of price
ggplot(diamonds) +
  geom_histogram(mapping=aes(x=price),binwidth=1000)
count(diamonds,cut_width(price,1000))
#there are negative value on price

#3.How many diamonds are 0.99 carat, how many are 1 carat? Explain
filter(diamonds,carat==0.99|carat==1) %>%
  group_by(carat) %>%
  summarise(n=n())
filter(diamonds,carat==0.99|carat==1) %>%
  ggplot(aes(x=carat)) +
  geom_bar()

## Missing Values
# Options to do when encountered unusual values on dataset
# 1. Drop the entire row with unusual value
diamonds2 <- diamonds %>%
  filter(between(y,3,20))

# 2. Replace unusual value with missing value
diamonds2 <- diamonds %>%
  mutate(y=ifelse(y<3|y>20,NA,y))

# Compare observations with missing values and recorded values 
# using visualization
nycflights13::flights %>%
  mutate(
    cancelled=is.na(dep_time),
    sched_hour=sched_dep_time %/% 100,
    sched_min=sched_dep_time %% 100,
    sched_dep_time=sched_hour+sched_min/60
  ) %>%
  ggplot(mapping=aes(sched_dep_time))+
   geom_freqpoly(
     mapping=aes(color=cancelled),
     binwidth=1/4
   )

## Covariation
## A Categorical and Continuouos Variable
ggplot(data=diamonds,mapping=aes(x=price))+
  geom_freqpoly(mapping=aes(color=cut),binwidth=500)

#Comparison between group is not useful because one group is much smaller than 
#the others
ggplot(diamonds)+
  geom_bar(mapping=aes(x=cut))
#It's hard to see distributions because the overall counts differs so much

# Swap y-axis from count to density to make comparison easier
ggplot(
  data=diamonds,
    mapping=aes(x=price,y=..density..)
  )+
   geom_freqpoly(mapping=aes(color=cut),binwidth=500)
#surprisingly, the fair (lowest quality) diamonds have the highest average price

# Visualize distribution of price by cut using geom_boxplot
ggplot(data=diamonds,mapping=aes(x=cut,y=price))+
  geom_boxplot()
#better quality diamonds are cheaper on average

#Reorder categorical variable to make more informative display
ggplot(data=mpg,mapping=aes(x=class,y=hwy))+
  geom_boxplot()
#reorder based on median value
ggplot(data=mpg)+
  geom_boxplot(
    mapping=aes(
      x=reorder(class,hwy,FUN=median),
      y=hwy
    )
  )

## Exercise
# 1. Improve visualization of the departure time of 
#    cancelled vs noncancelled flights 

# swap y-axis from count to sched dep_time then use geom_boxplot
nycflights13::flights %>%
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>%
  ggplot() +
  geom_boxplot(mapping = aes(y = sched_dep_time, x = cancelled))

# 2. What variable is most important in predicting the price of a diamond?
#    How is that variable correlated with cut?
#    How these two variables correlate to diamond's price?

# Try 4 variable: carat, color, clarity, and depth
# carat
ggplot(data = diamonds, mapping = aes(y=price,x=carat)) +
  geom_boxplot(mapping = aes(group=cut_width(carat,0.1)))

# color
ggplot(data = diamonds, mapping = aes(y=price, x=color)) +
  geom_boxplot()

# clarity
ggplot(data = diamonds, mapping = aes(y=price, x=clarity)) +
  geom_boxplot()

# depth
ggplot(data = diamonds, mapping = aes(y=price, x=depth)) +
  geom_boxplot(mapping = aes (group= cut_width(depth, 0.5)))

# Based on exploration above, carat is the most important predictor of price
# Now, look for relation between cut and carat
ggplot(data=diamonds, mapping=aes(y=carat, x=cut)) +
  geom_boxplot()

count(diamonds, cut, group=cut_width(carat, 1)) %>%
  ggplot(mapping=aes(y=n, x=cut)) +
  geom_col(mapping=aes(fill=group))

# 4. Install lvplot package, and use geom_lv 
#    to display distribution of price vs cut

install.packages("lvplot")
library(lvplot)

ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_lv()

ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_boxplot()

# 5. Compare geom_violin, faceted geom_histogram, and colored geom_freqpoly

# geom_violin
ggplot(data = diamonds) +
  geom_violin(mapping = aes(x = cut, y = price))

# faceted geom_histogram
ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = price)) +
  facet_wrap(~cut)

# colored geom_freqpoly
ggplot(data = diamonds) +
  geom_freqpoly(mapping = aes(x = price, color = cut))

# 6. Use ggbeeswarm packages to see the relationship between 
#    a continuous and categorical variable

install.packages("ggbeeswarm")
library(ggbeeswarm)
?`ggbeeswarm-package`
?ggbeeswarm

ggplot(data = mpg) +
  geom_quasirandom(mapping = aes(
    x = reorder(class, hwy, FUN = median), 
    y = hwy))

# Different method for distributing point: quasirandom, pseudorandom, 
# smiley, and frowney

# quasirandom
ggplot(data = mpg) +
  geom_quasirandom(mapping = aes(
    x = reorder(class, hwy, FUN = median), 
    y = hwy),
    method = "quasirandom"
  )

# pseudorandom
ggplot(data = mpg) +
  geom_quasirandom(mapping = aes(
    x = reorder(class, hwy, FUN = median), 
    y = hwy),
    method = "pseudorandom"
  )

# smiley
ggplot(data = mpg) +
  geom_quasirandom(mapping = aes(
    x = reorder(class, hwy, FUN = median),
    y = hwy),
    method = "smiley"
  )

# frowney
ggplot(data = mpg) +
  geom_quasirandom(mapping = aes(
    x = reorder(class, hwy, FUN = median),
    y = hwy),
    method = "frowney"
  )

## Two Categorical Variable

# To visualize covariation between categorical variables, use geom_count 
# to count the number of observations for each combinations.
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))

# Another approach using dplyr then visualize it with geom_tile
diamonds %>%
  count(color, cut) %>%
  ggplot(mapping = aes(x = color, y = cut)) +
   geom_tile(mapping = aes(fill = n))

## Exercise
# 1. Rescale count dataset to more clearly show the distribution of
#    cut within color, or color within cut

# Mutate proportion of cut within color
ex7521 <- count(diamonds, cut, color) %>%
  mutate(prop = n / sum(n))

# Visualize using geom_tile with fill = prop
ggplot(data = ex7521, mapping = aes(x = cut, y = color)) +
  geom_tile(mapping = aes(fill = prop)) +
  coord_flip()

# 2. Use geom_tile() together with dplyr to explore how average
#    flight delays vary by destination and month of year. What makes
#    the plot difficult to read? How could you improve it?

library(nycflights13)

# Group data by dest and month, 
# then get count and mean value of arr_delay from each group
ex7522 <- flights %>%
  group_by(dest, month) %>%
  summarise(
    count = n(),
    mean_arr_delay = mean(arr_delay, na.rm = T)
  )

ggplot(data = ex7522, mapping = aes(x = dest, y = as.factor(month))) +
  geom_tile(mapping = aes(fill = mean_arr_delay)) +
  coord_flip()

# Improvement agenda:
# 1) remove missing value
# 2) remove delayed flights with value less than or equal to 0
# 3) reserve group of dest with flights at least once per month
# 4) reorder dest based on it's mean delay value

ex7522.1 <- flights %>%
  na.omit() %>%
  filter(arr_delay > 0) %>%
  group_by(dest, month) %>%
  summarise(
    count = n(),
    mean_delay = mean(arr_delay)
  ) %>%
  group_by(dest) %>%
  mutate(count_dest = n()) %>%
  filter(n() >= 12) %>%
  ungroup() %>%
  mutate(dest = reorder (dest, mean_delay))

ggplot(data = ex7522.1, mapping = aes(
  x = as.factor(month), 
  y = dest)) + 
  geom_tile(mapping = aes(fill = mean_delay))

# 3. Why is it slightly better to use aes(x = color, y = cut) rather
#    than aes(x = cut, y = color) in the previous example?

# It's better to have higher n or concentration on y-axis


## Two Continuous Variable

# Recommended way to visualize covariation between two continuous variables
# is to use scatterplot with geom_point
ggplot(data = diamonds) +
  geom_point(mapping = aes(x = carat, y = price))

# When the size of database grows, points begin to overplot.
# Use alpha aesthetic can fix this problem
ggplot(data = diamonds) +
  geom_point(
    mapping = aes(x = carat, y = price),
    alpha = 1/100
  )

# Another solution is to use bin

# geom_bin2d
ggplot(data = smaller) +
  geom_bin2d(mapping = aes(x = carat, y = price))

# geom_hexbin
install.packages("hexbin")
library(hexbin)

ggplot(data = smaller) +
  geom_hex(mapping = aes(x = carat, y = price))

# Another option is to bin one continuous variable 
# so it acts like a categorical variable.
ggplot(data = smaller, mapping = aes(x = carat, y = price)) +
  geom_boxplot(
    mapping = aes(group = cut_width(carat, 0.1)), 
    orientation = "x"
  )

# In the last visualization, each group of boxplot summarise different number
# of observation. Use varwidth = T to make the width of the boxplot proportional
# to the number of points
ggplot(data = smaller, mapping = aes(x = carat, y = price)) +
  geom_boxplot(
    mapping = aes(group = cut_width(carat, 0.1)), 
    orientation = "x",
    varwidth = T
  )

# Another approach is to display approximately the same number of
# points in each bin using cut_number
ggplot(data = smaller, mapping = aes(x = carat, y = price)) +
  geom_boxplot(
    mapping = aes(group = cut_number(carat, 20)),
    orientation = "x",
  )

## Exercise
# 1. What need to be considered when using cut_width vs cut number
#    in geom_freqpoly?
#    How does that impact a visualization of the 2D distribution of
#    carat and price?

# cut_width
ggplot(data = smaller, mapping = aes(x = price)) +
  geom_freqpoly(mapping = aes(color = cut_width(carat, 1, boundary = 0)))

# cut_number
ggplot(data = smaller, mapping = aes(x = price)) +
  geom_freqpoly(mapping = aes(color = cut_number(carat, 5)))

# 2. Visualize the distribution of carat partitioned by price

# Partitioned using cut_width
ggplot(data = smaller, mapping = aes(x = cut_number(price, 8), y = carat)) +
  geom_boxplot() +
  coord_flip()

# Partitioned using cut_number
ggplot(data = smaller, mapping = aes(
  x = cut_width(price, 2500, boundary = 0), 
  y = carat)) +
  geom_boxplot(varwidth = T) +
  coord_flip()

# 4. Combine two technique to visualize the combined distribution of
#    cut, carat, and price
ggplot(data = smaller, mapping = aes(
  x = as.factor(cut_number(carat, 20)),
  y = cut)) +
  geom_tile(mapping = aes(fill = price)) +
  coord_flip()

ggplot(data = smaller, mapping = aes(
  x = cut_number(carat, 5),
  y = price,
  color = cut
)) +
  geom_boxplot(varwidth = T)


## Patterns and Models
# If a systematic relationship exists between two variables, it will 
# appear as a pattern. Questions to ask when a pattern is found:
# 1. Could this pattern be due to coincidence (random chance)?
# 2. How can you describe the relationship implied by the pattern?
# 3. How strong is the relationship implied by the pattern?
# 4. What other variables might affect the relationship?
# 5. Does the relationship change if you look at individual subgroups
#    of the data?

# A scatterplot of Old Faithful eruption lengths versus the wait time
# between eruptions shows a pattern: longer wait times are associated
# with longer eruptions
ggplot(data = faithful) +
  geom_point(mapping = aes(
    x = eruptions,
    y = waiting
  ))

# To understand the relationship between carat and price, first remove
# the very strong relationship between price and carat. The residual
# give a view price of diamond once the effect of carat has been removed.

library(modelr)
mod <- lm(log(price) ~ log(carat), diamonds)

diamonds3 <- diamonds %>%
  add_residuals(mod) %>%
  mutate(resid = exp(resid))

ggplot(data = diamonds3) +
  geom_point(mapping = aes(x = carat, y = resid))

ggplot(data = diamonds3) +
  geom_boxplot(mapping = aes(x = cut, y = resid))
